mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_url: media # Relative path from content folder.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: Site Name
        author:
            name: Your Name Here
            url: "http://example.com"
        google_analytics_id: UA-XXXXX-YY
        nav_hover: yes
        home_url: index.html
        menu:
            - title: Hero
              url: index.html
            - title: Sidebar
              url: sidebar.html
            - title: Blank
              url: blank.html
            - title: Dropdown
              url:
                - title: Another hero
                  url: another_index.html
                - title: Another sidebar
                  url: another_sidebar.html
                - title: Another blank
                  url: another_blank.html
        sidebar:
            - title: One
              url: one.html
            - title: Two
              url: two.html
